# Generated by Django 5.0.6 on 2026-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('channel_id', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True)),
                ('raw', models.JSONField(default=dict)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
