# Generated by Django 5.0.6 on 2026-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('공지사항', '공지사항'), ('과목평가', '과목평가'), ('취업지원', '취업지원'), ('행사/이벤트', '행사/이벤트'), ('프로젝트', '프로젝트')], default='공지사항', max_length=20),
        ),
    ]
